killian-mahe/shareyourproject

- resources/views/auth/login.blade.php
- resources/views/auth/passwords/confirm.blade.php
- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
- resources/views/auth/register.blade.php
- resources/views/auth/verify.blade.php
- resources/views/layouts/auth.blade.php
> 🐛 Removing navbar in auth views

- public/js/app.js
- resources/js/components/inputs/CustomInput.vue
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
> Adding previous value in auth forms

- .github/workflows/laravel.yml
- app/Http/Controllers/PostController.php
- app/User.php
- database/factories/UserFactory.php
- routes/web.php
- tests/Feature/PostTest.php
> ✨ Adding main controllers and tests

- app/Http/Controllers/PostController.php
- database/factories/PostFactory.php
- database/factories/ProjectFactory.php
- tests/Feature/PostTest.php
> Create post project factories

- app/Models/Project.php
- database/migrations/2020_08_25_211011_rename_project_owner_field.php
> 🗃 Renaming author column to owner

- app/User.php
> 🗃 Update User model relationships

- app/Http/Controllers/PostController.php
- app/Http/Controllers/ProjectController.php
- app/Http/Controllers/UserController.php
- database/factories/PostFactory.php
- database/factories/ProjectFactory.php
- resources/views/post/create.blade.php
- resources/views/post/edit.blade.php
- resources/views/post/list.blade.php
- resources/views/post/post.blade.php
- resources/views/project/create.blade.php
- resources/views/project/edit.blade.php
- resources/views/project/list.blade.php
- resources/views/project/public.blade.php
- resources/views/user/edit.blade.php
- resources/views/user/list.blade.php
- resources/views/user/user.blade.php
- routes/web.php
- tests/Unit/PostControllerTest.php
- tests/Unit/ProjectControllerTest.php
> Creating views architecture

- resources/sass/app.scss
- resources/sass/components/_button.scss
- resources/sass/components/_chat.scss
- resources/sass/components/_inputs.scss
> ♻️ Refactoring style file structure

- app/Models/Project.php
- app/User.php
- database/migrations/2020_08_30_193833_create_project_user_table.php
> Add user project relationship

- app/Http/Controllers/CommentController.php
- routes/web.php
- tests/Unit/CommentControllerTest.php
> Add comment controller

- public/css/app.css
- resources/sass/app.scss
- resources/sass/components/_nav.scss
- resources/views/layouts/app.blade.php
- resources/views/project/public.blade.php
> 💄 Adding Project Public Page Menu

- resources/views/project/about.blade.php
- resources/views/project/layout.blade.php
- resources/views/project/members.blade.php
- resources/views/project/public.blade.php
> Edit project public page structure

- app/Http/Controllers/ProjectController.php
- public/css/app.css
- resources/sass/components/_nav.scss
- resources/views/project/layout.blade.php
- routes/web.php
> Adding members/about routes

- app/Models/Project.php
- app/User.php
- database/factories/TechnologyFactory.php
- database/migrations/2020_09_08_203121_create_technologisables_table.php
- database/seeds/DatabaseSeeder.php
> Add technologies

- database/seeds/DatabaseSeeder.php
> 🗃 Updatin database seeding

- app/Models/Project.php
- app/User.php
- public/css/app.css
- resources/sass/components/_card.scss
- resources/sass/components/_nav.scss
- resources/views/project/layout.blade.php
- resources/views/project/members.blade.php
> Members project page

- database/factories/UserFactory.php
- database/migrations/2020_09_10_211130_add_title_users_table.php
- database/seeds/DatabaseSeeder.php
- resources/views/project/members.blade.php
Add title to user description in database
Update database seeder to add project members
Fix alternative orientation in members cards
> Add defaut profil picture and description to user

- public/css/app.css
- resources/sass/components/_card.scss
- resources/views/project/about.blade.php
> 💄 Adding Project About Page

- public/css/app.css
- resources/sass/components/_card.scss
- resources/sass/components/_generic.scss
- resources/sass/components/_nav.scss
- resources/views/components/cards/member.blade.php
- resources/views/project/about.blade.php
- resources/views/project/layout.blade.php
- resources/views/user/layout.blade.php
> 🎨 Improving Scss files

- resources/views/components/cards/member.blade.php
- resources/views/components/cards/project.blade.php
- resources/views/components/post.blade.php
- resources/views/project/layout.blade.php
- resources/views/user/layout.blade.php
> 🚚 Adding Users and Projects links

- app/Http/Kernel.php
- app/Http/Resources/User.php
- app/Providers/AppServiceProvider.php
- app/Providers/AuthServiceProvider.php
- app/User.php
- composer.json
- composer.lock
- config/auth.php
- public/js/app.js
- resources/js/components/cards/MemberCard.vue
- routes/api.php
> Create vue components project user

- resources/views/project/about.blade.php
> 💩 Fix Project About Page

- resources/views/layouts/app.blade.php
> 💄 Fix Nav Bar shadows

- app/Http/Kernel.php
- app/Http/Resources/Project.php
- public/js/app.js
- resources/js/components/cards/ProjectCard.vue
- resources/js/components/lists/ProjectList.vue
- resources/views/components/cards/project.blade.php
- resources/views/user/user.blade.php
- routes/api.php
> ✨ Adding dynamic components

- public/css/app.css
- public/js/app.js
- resources/js/components/lists/ProjectList.vue
- resources/sass/components/_button.scss
- resources/sass/components/_inputs.scss
- resources/views/layouts/app.blade.php
> 💄 Update Button style

- composer.lock
- package-lock.json
- package.json
> ⬆️ Upgrading dependencies

- app/Models/Post.php
- app/User.php
- database/migrations/2020_09_23_080649_create_post_user_table.php
- resources/views/components/post.blade.php
> Create liked post

- app/Http/Resources/Post.php
- public/css/app.css
- public/js/app.js
- resources/js/components/cards/PostCard.vue
- resources/views/components/post.blade.php
- routes/api.php
> Create post vue component

- app/Http/Controllers/HomeController.php
- public/js/app.js
- resources/js/components/cards/MemberCard.vue
- resources/js/components/cards/PostCard.vue
- resources/js/components/cards/ProjectCard.vue
- resources/views/layouts/app.blade.php
- resources/views/layouts/auth.blade.php
> Managing routes at logging

- app/Http/Controllers/SearchController.php
- app/Http/Resources/User.php
- package-lock.json
- package.json
- public/js/app.js
- resources/js/components/SearchBar.vue
- resources/views/layouts/app.blade.php
- routes/api.php
> ✨ Create search bar vue component

- app/Http/Controllers/SearchController.php
- app/Http/Controllers/UserController.php
- app/Http/Resources/Badge.php
- public/js/app.js
- resources/js/components/SearchBar.vue
- resources/js/components/inputs/BadgeSelectInput.vue
- resources/js/components/inputs/CustomInput.vue
- resources/js/components/inputs/SelectInput.vue
- resources/js/components/inputs/UserSelectInput.vue
- resources/js/components/utils/BadgeLabel.vue
- resources/views/project/create.blade.php
- routes/api.php
> New input components

- public/js/app.js
- resources/js/components/inputs/BadgeSelectInput.vue
> ✨ Adding Closing feature in badges

- public/css/app.css
- public/js/app.js
- resources/js/components/navigation/MobileNavBar.vue
- resources/js/components/navigation/TabletNavBar.vue
- resources/sass/components/_button.scss
- resources/sass/components/_card.scss
- resources/sass/components/_inputs.scss
- resources/sass/components/_nav.scss
- resources/views/layouts/app.blade.php
> Update links in navbar

- app/Models/Image.php
- app/Models/Post.php
- app/Models/Video.php
- database/migrations/2020_11_05_201053_create_permission_tables.php
- database/migrations/2020_11_08_150031_create_photo_video_table.php
> Create video photo model

- resources/js/bootstrap.js
- resources/js/components/navigation/PersonalMenu.vue
- resources/sass/components/_generic.scss
- resources/views/layouts/app.blade.php
> Create personal menu

- app/Models/Settings.php
- app/User.php
- database/migrations/2021_01_11_182730_create_settings_table.php
> Create user settings

- public/js/app.js
- resources/js/components/cards/PostCard.vue
- resources/js/components/inputs/TextArea.vue
> ✨ Adding Key Events for Text Area

- public/js/app.js
- resources/js/components/inputs/PostCreation.vue
> 🔥 Removing Photo/Video select

- resources/views/user/user.blade.php
> ✏️ Fix gender

- app/Providers/AppServiceProvider.php
> ✨ Update boot rules

- app/Http/Controllers/ProjectController.php
> 🐛 Add owner to members

- app/Http/Controllers/FeedController.php
- resources/views/project/public.blade.php
- resources/views/user/user.blade.php
> ✨ Sort projects by creation date
